# Aegis™ Method Core Configuration

code: builder
name: "Aegis Builder: Aegis Builder - Agent, Workflow and Module Builder"
default_selected: false # This module will not be selected by default for new installations

header: "Aegis Builder Module (ABM) Module Configuration"
subheader: "Configure the settings for the ABM Factory!\nThe agent, workflow and module builder for Aegis™"

# Variables from Core Config inserted:
## user_name
## communication_language
## output_folder
## aegis_folder
## install_user_docs
## kb_install

custom_stand_alone_location:
  prompt: "Where do custom agents and workflows get stored?"
  default: "aegis-custom-src"
  result: "{project-root}/{value}"

custom_module_location:
  prompt: "Where do custom modules get stored?"
  default: "aegis-custom-modules-src"
  result: "{project-root}/{value}"
